### ISSUE TITLE
[1pt] Choose assets - group task

### ISSUE THREAD

**Issue by jaimevillegas** [jaimevillegas/Module-2-Capstone-Project#19]
Choose images, text, icons, fonts.

**Comment by jaimevillegas** [comment]
I would suggest using a pattern as a background of the webpage.

This can work:

`background-color: #1d1d1d;
background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'%3E%3Cg fill='%23393936' fill-opacity='0.4'%3E%3Cpolygon fill-rule='evenodd' points='8 4 12 6 8 8 6 12 4 8 0 6 4 4 6 0 8 4'/%3E%3C/g%3E%3C/svg%3E");`

Or something from this webpage:

https://heropatterns.com/

**Comment by BahirHakimy** [comment]
### I would also suggest taking some inspiration from this image as well, it has a nice color theme that we can use for our project.

**Comment by BahirHakimy** [comment]
I would suggest using this image as an inspiration source and also we can use the same color theme which is in the image.
https://file.mockplus.com/image/2019/07/5e98f561-8a49-4e1d-ba50-77a437f0c83f.png

**Comment by jaimevillegas** [comment]
I suggest the following color palletes:

https://colorhunt.co/palette/0a26471442722052952c74b3

https://colorhunt.co/palette/0f044c141e61787a91eeeeee

https://colorhunt.co/palette/1a1a2e16213e0f3460e94560

**Comment by jaimevillegas** [comment]
I suggest using Font Awesome for the icons:

https://fontawesome.com/

**Comment by jaimevillegas** [comment]
I suggest using Font Awesome for the icons:

https://fontawesome.com/

**Comment by BahirHakimy** [comment]
We can use Tailwind CSS for styling

**Comment by jaimevillegas** [comment]
We can use this font:

https://www.behance.net/gallery/14884671/AQUA-GROTESQUE-TYPEFACE

**Comment by jaimevillegas** [comment]
I recommend this website to get some inspiration on UI elements:

https://uiverse.io/
