### ISSUE TITLE
Kanban Project Setup

### ISSUE THREAD

**Issue by jaimevillegas** [jaimevillegas/Module-2-Capstone-Project#21]
Hi there!

We are 2 persons on the team: @BahirHakimy  and Me!

This is the link to the Kanban Project:

https://github.com/jaimevillegas/Module-2-Capstone-Project/projects/1

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 
Congratulations! 🎉 
## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- In future,  It would be better to update all Card titles with Student A or B, this will help you find task for each student easily, currently, task for each student is assigned properly well-done 👏🏿 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
